---
- name: <<< PLAYBOOK 03 >>> APT. INSTALL POSTGRESQL | Install Client.
  hosts: caservers
  become: true
  tasks:
  - name: INSTALL POSTGRESQL. Install Client.
    ansible.builtin.apt:
      name: acl,postgresql-client,python3-cryptography
      state: present
      update_cache: false

- name: <<< PLAYBOOK 03 >>> APT. INSTALL POSTGRESQL | Install Server.
  hosts: cprodbserver
  become: true
  tasks:
  - name: INSTALL POSTGRESQL. Install Server.
    ansible.builtin.apt:
      name: postgresql,python3-psycopg2,acl
      state: present
      update_cache: false
